Skip adding DHCP options for IPv6
NIOS does not allow to set DHCP options for IPv6 over WAPI on network
creation and raises:
IBDataConflictError: IB.Data.Conflict:Set the option DHCP.routers from
the General Properties section.

So skipping setting DHCP options for IPv6.